import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import { getGenresOfMovie } from "@/lib/getMovies";
import Header from "@/components/Header";
import { Genres } from "@/typings";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const genreMovies = await getGenresOfMovie();

	return (
		<html lang='en'>
			<body
				className={cn(
					"bg-white dark:bg-[#1a1c29]",
					inter.className,
				)}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<Header genreMovies={genreMovies} />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
